import { Injectable } from '@angular/core';

export class CashFlows {
    "Issuer Group": string;
    "Issuer Group Code": string;
    "Security Code": string;
    "Instrument": string;
    "Spread": string;
    "Maturity Date": string;
    "Industry": string;
    "Secured/Unsecured": string;
    "Deal Type" : string;
    "Sponsor/Nonsponsor" : string;
    "Cash Flow Date": string;
    "Cash Flow Amount" : string;
    "Event" : string;
    "Symbol" : string;
    "IRR" : string;
}

export class IRRs {
    "Issuer Group": string;
    "Issuer Group Code": string;
    "Security Code": string;
    "Instrument": string;
    "Spread": string;
    "Maturity Date": string;
    "Industry": string;
    "Secured/Unsecured": string;
    "Deal Type" : string;
    "Sponsor/Nonsponsor" : string;
    "Cash Flow Date": string;
    "Cash Flow Amount" : number;
    "Event" : string;
    "Symbol" : string;
    "IRR" : number;
}

let cashflow: CashFlows[] = [
	{
		"Issuer Group": "Ardent Health Partners",
		"Issuer Group Code": "M",
		"Security Code": "LX171898",
		"Instrument": "Unsecured TL",
		"Spread": "L + 850",
		"Maturity Date": "03-01-23",
		"Industry": "Healthcare",
		"Secured/Unsecured": "Unsecured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-01-18",
		"Cash Flow Amount": "-2143360",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Ardent Health Partners",
		"Issuer Group Code": "M",
		"Security Code": "LX171898",
		"Instrument": "Unsecured TL",
		"Spread": "L + 850",
		"Maturity Date": "03-01-23",
		"Industry": "Healthcare",
		"Secured/Unsecured": "Unsecured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "2190476.44",
		"Event": "MV",
		"Symbol": "M",
		"IRR": "0.3029"
	},
	{
		"Issuer Group": "Avaya Holdings Corp",
		"Issuer Group Code": "O",
		"Security Code": "LX174166",
		"Instrument": "TLB",
		"Spread": "L + 475",
		"Maturity Date": "12-15-24",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-09-18",
		"Cash Flow Amount": "-2026578.75",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Avaya Holdings Corp",
		"Issuer Group Code": "O",
		"Security Code": "LX174166",
		"Instrument": "TLB",
		"Spread": "L + 475",
		"Maturity Date": "12-15-24",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "5022.5",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Avaya Holdings Corp",
		"Issuer Group Code": "O",
		"Security Code": "LX174166",
		"Instrument": "TLB",
		"Spread": "L + 475",
		"Maturity Date": "12-15-24",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "2016502.36",
		"Event": "MV",
		"Symbol": "O",
		"IRR": "-0.0406"
	},
	{
		"Issuer Group": "California Resources Corp",
		"Issuer Group Code": "P",
		"Security Code": "LX169569",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "12-31-22",
		"Industry": "Energy",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-09-18",
		"Cash Flow Amount": "-1100598.75",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "California Resources Corp",
		"Issuer Group Code": "P",
		"Security Code": "LX169569",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "12-31-22",
		"Industry": "Energy",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-14-18",
		"Cash Flow Amount": "-296456.25",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "California Resources Corp",
		"Issuer Group Code": "P",
		"Security Code": "LX169569",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "12-31-22",
		"Industry": "Energy",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-16-18",
		"Cash Flow Amount": "-341880",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "California Resources Corp",
		"Issuer Group Code": "P",
		"Security Code": "LX169569",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "12-31-22",
		"Industry": "Energy",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "1732982.4",
		"Event": "MV",
		"Symbol": "P",
		"IRR": "-0.0613"
	},
	{
		"Issuer Group": "Carlisle Foods",
		"Issuer Group Code": "V",
		"Security Code": "Carlisle_2L",
		"Instrument": "2nd Lien",
		"Spread": "L + 775",
		"Maturity Date": "03-20-26",
		"Industry": "Food & Beverage",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-20-18",
		"Cash Flow Amount": "-1067220",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Carlisle Foods",
		"Issuer Group Code": "V",
		"Security Code": "Carlisle_2L",
		"Instrument": "2nd Lien",
		"Spread": "L + 775",
		"Maturity Date": "03-20-26",
		"Industry": "Food & Beverage",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "1070396.25",
		"Event": "MV",
		"Symbol": "V",
		"IRR": "0.1036"
	},
	{
		"Issuer Group": "Clarion Events Ltd",
		"Issuer Group Code": "J",
		"Security Code": "LX171498",
		"Instrument": "TLB",
		"Spread": "L + 500",
		"Maturity Date": "09-30-24",
		"Industry": "Business Services",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "02-16-18",
		"Cash Flow Amount": "-579180",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Clarion Events Ltd",
		"Issuer Group Code": "J",
		"Security Code": "LX171498",
		"Instrument": "TLB",
		"Spread": "L + 500",
		"Maturity Date": "09-30-24",
		"Industry": "Business Services",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "582873.75",
		"Event": "MV",
		"Symbol": "J",
		"IRR": "0.0554"
	},
	{
		"Issuer Group": "Contura Energy Inc",
		"Issuer Group Code": "W",
		"Security Code": "LX160842",
		"Instrument": "TL",
		"Spread": "L + 500",
		"Maturity Date": "11-10-25",
		"Industry": "Industrials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-20-18",
		"Cash Flow Amount": "-681700",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Contura Energy Inc",
		"Issuer Group Code": "W",
		"Security Code": "LX160842",
		"Instrument": "TL",
		"Spread": "L + 500",
		"Maturity Date": "11-10-25",
		"Industry": "Industrials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "1757.11",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Contura Energy Inc",
		"Issuer Group Code": "W",
		"Security Code": "LX160842",
		"Instrument": "TL",
		"Spread": "L + 500",
		"Maturity Date": "11-10-25",
		"Industry": "Industrials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "676126.78",
		"Event": "MV",
		"Symbol": "W",
		"IRR": "-0.1700"
	},
	{
		"Issuer Group": "Corfin Industries",
		"Issuer Group Code": "I",
		"Security Code": "CORFIN_REV",
		"Instrument": "Revolver",
		"Spread": "L + 650",
		"Maturity Date": "02-15-24",
		"Industry": "Industrials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Sole",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "50.93",
		"Event": "43B",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Corfin Industries",
		"Issuer Group Code": "I",
		"Security Code": "CORFIN_REV",
		"Instrument": "Revolver",
		"Spread": "L + 650",
		"Maturity Date": "02-15-24",
		"Industry": "Industrials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Sole",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "92.12",
		"Event": "IAC",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Corfin Industries",
		"Issuer Group Code": "I",
		"Security Code": "CORFIN_TL",
		"Instrument": "TL",
		"Spread": "L + 650",
		"Maturity Date": "02-15-24",
		"Industry": "Industrials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Sole",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "02-15-18",
		"Cash Flow Amount": "-855540",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Corfin Industries",
		"Issuer Group Code": "I",
		"Security Code": "CORFIN_TL",
		"Instrument": "TL",
		"Spread": "L + 650",
		"Maturity Date": "02-15-24",
		"Industry": "Industrials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Sole",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "8290.59",
		"Event": "IAC",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Corfin Industries",
		"Issuer Group Code": "I",
		"Security Code": "CORFIN_TL",
		"Instrument": "TL",
		"Spread": "L + 650",
		"Maturity Date": "02-15-24",
		"Industry": "Industrials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Sole",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "856157.97",
		"Event": "MV",
		"Symbol": "I",
		"IRR": "0.0913"
	},
	{
		"Issuer Group": "EIG Investors Corp",
		"Issuer Group Code": "F",
		"Security Code": "LX171112",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "01-31-25",
		"Industry": "Financials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "01-31-18",
		"Cash Flow Amount": "-215190",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "EIG Investors Corp",
		"Issuer Group Code": "F",
		"Security Code": "LX171112",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "01-31-25",
		"Industry": "Financials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "217350",
		"Event": "MV",
		"Symbol": "F",
		"IRR": "0.0637"
	},
	{
		"Issuer Group": "Endemol",
		"Issuer Group Code": "Q",
		"Security Code": "LX139558",
		"Instrument": "TL",
		"Spread": "L + 575",
		"Maturity Date": "08-13-21",
		"Industry": "Media/Entertainment",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-09-18",
		"Cash Flow Amount": "-404007.5",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Endemol",
		"Issuer Group Code": "Q",
		"Security Code": "LX139558",
		"Instrument": "TL",
		"Spread": "L + 575",
		"Maturity Date": "08-13-21",
		"Industry": "Media/Entertainment",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-14-18",
		"Cash Flow Amount": "-606512.5",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Endemol",
		"Issuer Group Code": "Q",
		"Security Code": "LX139558",
		"Instrument": "TL",
		"Spread": "L + 575",
		"Maturity Date": "08-13-21",
		"Industry": "Media/Entertainment",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-26-18",
		"Cash Flow Amount": "-303757.5",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Endemol",
		"Issuer Group Code": "Q",
		"Security Code": "LX139558",
		"Instrument": "TL",
		"Spread": "L + 575",
		"Maturity Date": "08-13-21",
		"Industry": "Media/Entertainment",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "-1041.3399999999999",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Endemol",
		"Issuer Group Code": "Q",
		"Security Code": "LX139558",
		"Instrument": "TL",
		"Spread": "L + 575",
		"Maturity Date": "08-13-21",
		"Industry": "Media/Entertainment",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "1041.3399999999999",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Endemol",
		"Issuer Group Code": "Q",
		"Security Code": "LX139558",
		"Instrument": "TL",
		"Spread": "L + 575",
		"Maturity Date": "08-13-21",
		"Industry": "Media/Entertainment",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "-1563.31",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Endemol",
		"Issuer Group Code": "Q",
		"Security Code": "LX139558",
		"Instrument": "TL",
		"Spread": "L + 575",
		"Maturity Date": "08-13-21",
		"Industry": "Media/Entertainment",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "1563.31",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Endemol",
		"Issuer Group Code": "Q",
		"Security Code": "LX139558",
		"Instrument": "TL",
		"Spread": "L + 575",
		"Maturity Date": "08-13-21",
		"Industry": "Media/Entertainment",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "782.95",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Endemol",
		"Issuer Group Code": "Q",
		"Security Code": "LX139558",
		"Instrument": "TL",
		"Spread": "L + 575",
		"Maturity Date": "08-13-21",
		"Industry": "Media/Entertainment",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "2604.65",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Endemol",
		"Issuer Group Code": "Q",
		"Security Code": "LX139558",
		"Instrument": "TL",
		"Spread": "L + 575",
		"Maturity Date": "08-13-21",
		"Industry": "Media/Entertainment",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "1306906.29",
		"Event": "MV",
		"Symbol": "Q",
		"IRR": "-0.0679"
	},
	{
		"Issuer Group": "Frontier Communications",
		"Issuer Group Code": "L",
		"Security Code": "LX164782",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "06-17-24",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "02-28-18",
		"Cash Flow Amount": "-369325",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Frontier Communications",
		"Issuer Group Code": "L",
		"Security Code": "LX164782",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "06-17-24",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-06-18",
		"Cash Flow Amount": "-388090",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Frontier Communications",
		"Issuer Group Code": "L",
		"Security Code": "LX164782",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "06-17-24",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-09-18",
		"Cash Flow Amount": "-430650",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Frontier Communications",
		"Issuer Group Code": "L",
		"Security Code": "LX164782",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "06-17-24",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-14-18",
		"Cash Flow Amount": "-590040",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Frontier Communications",
		"Issuer Group Code": "L",
		"Security Code": "LX164782",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "06-17-24",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-20-18",
		"Cash Flow Amount": "-353430",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Frontier Communications",
		"Issuer Group Code": "L",
		"Security Code": "LX164782",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "06-17-24",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-26-18",
		"Cash Flow Amount": "-176762.5",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Frontier Communications",
		"Issuer Group Code": "L",
		"Security Code": "LX164782",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "06-17-24",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "896.98",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Frontier Communications",
		"Issuer Group Code": "L",
		"Security Code": "LX164782",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "06-17-24",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "1092.96",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Frontier Communications",
		"Issuer Group Code": "L",
		"Security Code": "LX164782",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "06-17-24",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "1497.49",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Frontier Communications",
		"Issuer Group Code": "L",
		"Security Code": "LX164782",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "06-17-24",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "1929.65",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Frontier Communications",
		"Issuer Group Code": "L",
		"Security Code": "LX164782",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "06-17-24",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "449.75",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Frontier Communications",
		"Issuer Group Code": "L",
		"Security Code": "LX164782",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "06-17-24",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "-989.95",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Frontier Communications",
		"Issuer Group Code": "L",
		"Security Code": "LX164782",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "06-17-24",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "989.95",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Frontier Communications",
		"Issuer Group Code": "L",
		"Security Code": "LX164782",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "06-17-24",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "-939.7",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Frontier Communications",
		"Issuer Group Code": "L",
		"Security Code": "LX164782",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "06-17-24",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "939.7",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Frontier Communications",
		"Issuer Group Code": "L",
		"Security Code": "LX164782",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "06-17-24",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "2295663.52",
		"Event": "MV",
		"Symbol": "L",
		"IRR": "-0.0530"
	},
	{
		"Issuer Group": "Genex",
		"Issuer Group Code": "N",
		"Security Code": "LX171682",
		"Instrument": "2nd Lien",
		"Spread": "L + 700",
		"Maturity Date": "03-06-26",
		"Industry": "Healthcare",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-06-18",
		"Cash Flow Amount": "-233640",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Genex",
		"Issuer Group Code": "N",
		"Security Code": "LX171682",
		"Instrument": "2nd Lien",
		"Spread": "L + 700",
		"Maturity Date": "03-06-26",
		"Industry": "Healthcare",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "236394.12",
		"Event": "MV",
		"Symbol": "N",
		"IRR": "0.1866"
	},
	{
		"Issuer Group": "ICR",
		"Issuer Group Code": " LLC",
		"Security Code": "Z",
		"Instrument": "ICR_TL",
		"Spread": "TL",
		"Maturity Date": "L + 550",
		"Industry": "03-26-25",
		"Secured/Unsecured": "Business Services",
		"Deal Type": "Secured",
		"Sponsor/Nonsponsor": "Sole",
		"Cash Flow Date": "Sponsor",
		"Cash Flow Amount": "03-26-18",
		"Event": "-1373960",
		"Symbol": "TRD",
		"IRR": ""
	},
	{
		"Issuer Group": "ICR",
		"Issuer Group Code": " LLC",
		"Security Code": "Z",
		"Instrument": "ICR_TL",
		"Spread": "TL",
		"Maturity Date": "L + 550",
		"Industry": "03-26-25",
		"Secured/Unsecured": "Business Services",
		"Deal Type": "Secured",
		"Sponsor/Nonsponsor": "Sole",
		"Cash Flow Date": "Sponsor",
		"Cash Flow Amount": "03-31-18",
		"Event": "1375779.2",
		"Symbol": "MV",
		"IRR": "Z"
	},
	{
		"Issuer Group": "InnovaCare",
		"Issuer Group Code": "S",
		"Security Code": "Innovacare_DDTL",
		"Instrument": "DDTL",
		"Spread": "L + 625",
		"Maturity Date": "03-14-23",
		"Industry": "Healthcare",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Sole",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-15-18",
		"Cash Flow Amount": "-12640",
		"Event": "07P",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "InnovaCare",
		"Issuer Group Code": "S",
		"Security Code": "Innovacare_DDTL",
		"Instrument": "DDTL",
		"Spread": "L + 625",
		"Maturity Date": "03-14-23",
		"Industry": "Healthcare",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Sole",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-30-18",
		"Cash Flow Amount": "263.33",
		"Event": "43B",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "InnovaCare",
		"Issuer Group Code": "S",
		"Security Code": "Innovacare_Rev",
		"Instrument": "Revolver",
		"Spread": "L + 625",
		"Maturity Date": "03-14-23",
		"Industry": "Healthcare",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Sole",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-30-18",
		"Cash Flow Amount": "65.83",
		"Event": "43B",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "InnovaCare",
		"Issuer Group Code": "S",
		"Security Code": "Innovacare_TL",
		"Instrument": "TL",
		"Spread": "L + 625",
		"Maturity Date": "03-14-23",
		"Industry": "Healthcare",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-15-18",
		"Cash Flow Amount": "-3617180",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "InnovaCare",
		"Issuer Group Code": "S",
		"Security Code": "Innovacare_TL",
		"Instrument": "TL",
		"Spread": "L + 625",
		"Maturity Date": "03-14-23",
		"Industry": "Healthcare",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "3631776.54",
		"Event": "MV",
		"Symbol": "S",
		"IRR": "0.0145"
	},
	{
		"Issuer Group": "Intelsat",
		"Issuer Group Code": "X",
		"Security Code": "LX169475",
		"Instrument": "TLB3",
		"Spread": "L + 375",
		"Maturity Date": "11-27-23",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-20-18",
		"Cash Flow Amount": "-2002500",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Intelsat",
		"Issuer Group Code": "X",
		"Security Code": "LX169475",
		"Instrument": "TLB3",
		"Spread": "L + 375",
		"Maturity Date": "11-27-23",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-21-18",
		"Cash Flow Amount": "-905130",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Intelsat",
		"Issuer Group Code": "X",
		"Security Code": "LX169475",
		"Instrument": "TLB3",
		"Spread": "L + 375",
		"Maturity Date": "11-27-23",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-26-18",
		"Cash Flow Amount": "-1085707.5",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Intelsat",
		"Issuer Group Code": "X",
		"Security Code": "LX169475",
		"Instrument": "TLB3",
		"Spread": "L + 375",
		"Maturity Date": "11-27-23",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "1808000",
		"Event": "MV",
		"Symbol": "X",
		"IRR": "0.0000"
	},
	{
		"Issuer Group": "Iridium Communications",
		"Issuer Group Code": "T",
		"Security Code": "46269CAA0",
		"Instrument": "Sr Nts",
		"Spread": "10.25%",
		"Maturity Date": "04-15-23",
		"Industry": "Telecom",
		"Secured/Unsecured": "Unsecured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-16-18",
		"Cash Flow Amount": "-363000",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Iridium Communications",
		"Issuer Group Code": "T",
		"Security Code": "46269CAA0",
		"Instrument": "Sr Nts",
		"Spread": "10.25%",
		"Maturity Date": "04-15-23",
		"Industry": "Telecom",
		"Secured/Unsecured": "Unsecured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "374016.04",
		"Event": "MV",
		"Symbol": "T",
		"IRR": "1.0698"
	},
	{
		"Issuer Group": "Loparex",
		"Issuer Group Code": "AA",
		"Security Code": "LX172480",
		"Instrument": "TLB",
		"Spread": "L + 425",
		"Maturity Date": "04-11-25",
		"Industry": "Paper & Packaging",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "-203975",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Loparex",
		"Issuer Group Code": "AA",
		"Security Code": "LX172480",
		"Instrument": "TLB",
		"Spread": "L + 425",
		"Maturity Date": "04-11-25",
		"Industry": "Paper & Packaging",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "203975",
		"Event": "MV",
		"Symbol": "AA",
		"IRR": "0.0000"
	},
	{
		"Issuer Group": "MedRisk",
		"Issuer Group Code": "C",
		"Security Code": "LX170958",
		"Instrument": "2nd Lien",
		"Spread": "L + 675",
		"Maturity Date": "01-23-26",
		"Industry": "Healthcare",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "01-25-18",
		"Cash Flow Amount": "-202980",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "MedRisk",
		"Issuer Group Code": "C",
		"Security Code": "LX170958",
		"Instrument": "2nd Lien",
		"Spread": "L + 675",
		"Maturity Date": "01-23-26",
		"Industry": "Healthcare",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "1673.09",
		"Event": "IAC",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "MedRisk",
		"Issuer Group Code": "C",
		"Security Code": "LX170958",
		"Instrument": "2nd Lien",
		"Spread": "L + 675",
		"Maturity Date": "01-23-26",
		"Industry": "Healthcare",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "203149.32",
		"Event": "MV",
		"Symbol": "C",
		"IRR": "0.0521"
	},
	{
		"Issuer Group": "Meredith",
		"Issuer Group Code": "A",
		"Security Code": "589433AA9",
		"Instrument": "Sr Nts",
		"Spread": "6.88%",
		"Maturity Date": "02-01-26",
		"Industry": "Media/Entertainment",
		"Secured/Unsecured": "Unsecured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "01-19-18",
		"Cash Flow Amount": "-51000",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Meredith",
		"Issuer Group Code": "A",
		"Security Code": "589433AA9",
		"Instrument": "Sr Nts",
		"Spread": "6.88%",
		"Maturity Date": "02-01-26",
		"Industry": "Media/Entertainment",
		"Secured/Unsecured": "Unsecured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "01-19-18",
		"Cash Flow Amount": "52147.5",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Meredith",
		"Issuer Group Code": "A",
		"Security Code": "589433AA9",
		"Instrument": "Sr Nts",
		"Spread": "6.88%",
		"Maturity Date": "02-01-26",
		"Industry": "Media/Entertainment",
		"Secured/Unsecured": "Unsecured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "0",
		"Event": "MV",
		"Symbol": "A",
		"IRR": "0.0000"
	},
	{
		"Issuer Group": "Navitas Midstream",
		"Issuer Group Code": "K",
		"Security Code": "LX170023",
		"Instrument": "TLB",
		"Spread": "L + 450",
		"Maturity Date": "12-13-24",
		"Industry": "Energy",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "02-22-18",
		"Cash Flow Amount": "-476187.5",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Navitas Midstream",
		"Issuer Group Code": "K",
		"Security Code": "LX170023",
		"Instrument": "TLB",
		"Spread": "L + 450",
		"Maturity Date": "12-13-24",
		"Industry": "Energy",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "02-26-18",
		"Cash Flow Amount": "-145362.5",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Navitas Midstream",
		"Issuer Group Code": "K",
		"Security Code": "LX170023",
		"Instrument": "TLB",
		"Spread": "L + 450",
		"Maturity Date": "12-13-24",
		"Industry": "Energy",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-09-18",
		"Cash Flow Amount": "-606000",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Navitas Midstream",
		"Issuer Group Code": "K",
		"Security Code": "LX170023",
		"Instrument": "TLB",
		"Spread": "L + 450",
		"Maturity Date": "12-13-24",
		"Industry": "Energy",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-21-18",
		"Cash Flow Amount": "-370.15",
		"Event": "35B",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Navitas Midstream",
		"Issuer Group Code": "K",
		"Security Code": "LX170023",
		"Instrument": "TLB",
		"Spread": "L + 450",
		"Maturity Date": "12-13-24",
		"Industry": "Energy",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-21-18",
		"Cash Flow Amount": "1298.3499999999999",
		"Event": "DCP",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Navitas Midstream",
		"Issuer Group Code": "K",
		"Security Code": "LX170023",
		"Instrument": "TLB",
		"Spread": "L + 450",
		"Maturity Date": "12-13-24",
		"Industry": "Energy",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "1515",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Navitas Midstream",
		"Issuer Group Code": "K",
		"Security Code": "LX170023",
		"Instrument": "TLB",
		"Spread": "L + 450",
		"Maturity Date": "12-13-24",
		"Industry": "Energy",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "1550",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Navitas Midstream",
		"Issuer Group Code": "K",
		"Security Code": "LX170023",
		"Instrument": "TLB",
		"Spread": "L + 450",
		"Maturity Date": "12-13-24",
		"Industry": "Energy",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "-362.5",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Navitas Midstream",
		"Issuer Group Code": "K",
		"Security Code": "LX170023",
		"Instrument": "TLB",
		"Spread": "L + 450",
		"Maturity Date": "12-13-24",
		"Industry": "Energy",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "362.5",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Navitas Midstream",
		"Issuer Group Code": "K",
		"Security Code": "LX170023",
		"Instrument": "TLB",
		"Spread": "L + 450",
		"Maturity Date": "12-13-24",
		"Industry": "Energy",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "-1187.5",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Navitas Midstream",
		"Issuer Group Code": "K",
		"Security Code": "LX170023",
		"Instrument": "TLB",
		"Spread": "L + 450",
		"Maturity Date": "12-13-24",
		"Industry": "Energy",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "1187.5",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Navitas Midstream",
		"Issuer Group Code": "K",
		"Security Code": "LX170023",
		"Instrument": "TLB",
		"Spread": "L + 450",
		"Maturity Date": "12-13-24",
		"Industry": "Energy",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "1220648.1100000001",
		"Event": "MV",
		"Symbol": "K",
		"IRR": "-0.0293"
	},
	{
		"Issuer Group": "PetVet LLC",
		"Issuer Group Code": "G",
		"Security Code": "LX170766",
		"Instrument": "2nd Lien",
		"Spread": "L + 625",
		"Maturity Date": "01-30-26",
		"Industry": "Consumer",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "02-01-18",
		"Cash Flow Amount": "-358200",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "PetVet LLC",
		"Issuer Group Code": "G",
		"Security Code": "LX170766",
		"Instrument": "2nd Lien",
		"Spread": "L + 625",
		"Maturity Date": "01-30-26",
		"Industry": "Consumer",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-15-18",
		"Cash Flow Amount": "1332.38",
		"Event": "IAC",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "PetVet LLC",
		"Issuer Group Code": "G",
		"Security Code": "LX170766",
		"Instrument": "2nd Lien",
		"Spread": "L + 625",
		"Maturity Date": "01-30-26",
		"Industry": "Consumer",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "358250.96",
		"Event": "MV",
		"Symbol": "G",
		"IRR": "0.0246"
	},
	{
		"Issuer Group": "Safe Fleet",
		"Issuer Group Code": "B",
		"Security Code": "LX170944",
		"Instrument": "2nd Lien",
		"Spread": "L + 675",
		"Maturity Date": "02-01-26",
		"Industry": "Industrials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "01-23-18",
		"Cash Flow Amount": "-317405",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Safe Fleet",
		"Issuer Group Code": "B",
		"Security Code": "LX170944",
		"Instrument": "2nd Lien",
		"Spread": "L + 675",
		"Maturity Date": "02-01-26",
		"Industry": "Industrials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "317405",
		"Event": "MV",
		"Symbol": "B",
		"IRR": "0.0000"
	},
	{
		"Issuer Group": "Skillsoft Corp",
		"Issuer Group Code": "D",
		"Security Code": "LX136501",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "04-28-21",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "01-25-18",
		"Cash Flow Amount": "-175950",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Skillsoft Corp",
		"Issuer Group Code": "D",
		"Security Code": "LX136501",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "04-28-21",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "02-26-18",
		"Cash Flow Amount": "-178710",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Skillsoft Corp",
		"Issuer Group Code": "D",
		"Security Code": "LX136501",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "04-28-21",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-06-18",
		"Cash Flow Amount": "-227.26",
		"Event": "35B",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Skillsoft Corp",
		"Issuer Group Code": "D",
		"Security Code": "LX136501",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "04-28-21",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-06-18",
		"Cash Flow Amount": "919.13",
		"Event": "DCP",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Skillsoft Corp",
		"Issuer Group Code": "D",
		"Security Code": "LX136501",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "04-28-21",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-08-18",
		"Cash Flow Amount": "-261.61",
		"Event": "38B",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Skillsoft Corp",
		"Issuer Group Code": "D",
		"Security Code": "LX136501",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "04-28-21",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "697.61",
		"Event": "IAC",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Skillsoft Corp",
		"Issuer Group Code": "D",
		"Security Code": "LX136501",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "04-28-21",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "31.13",
		"Event": "IAC",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Skillsoft Corp",
		"Issuer Group Code": "D",
		"Security Code": "LX136501",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "04-28-21",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "660.9",
		"Event": "IAC",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Skillsoft Corp",
		"Issuer Group Code": "D",
		"Security Code": "LX136501",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "04-28-21",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "32.85",
		"Event": "IAC",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Skillsoft Corp",
		"Issuer Group Code": "D",
		"Security Code": "LX136501",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "04-28-21",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "351056.94",
		"Event": "MV",
		"Symbol": "D",
		"IRR": "-0.0363"
	},
	{
		"Issuer Group": "Stepstone",
		"Issuer Group Code": "R",
		"Security Code": "LX172326",
		"Instrument": "TLB",
		"Spread": "L + 400",
		"Maturity Date": "03-27-25",
		"Industry": "Financials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-14-18",
		"Cash Flow Amount": "-299495",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Stepstone",
		"Issuer Group Code": "R",
		"Security Code": "LX172326",
		"Instrument": "TLB",
		"Spread": "L + 400",
		"Maturity Date": "03-27-25",
		"Industry": "Financials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "299495",
		"Event": "MV",
		"Symbol": "R",
		"IRR": "0.0000"
	},
	{
		"Issuer Group": "Subsea Global",
		"Issuer Group Code": "AB",
		"Security Code": "Subsea_TL",
		"Instrument": "TL",
		"Spread": "L + 700",
		"Maturity Date": "03-28-23",
		"Industry": "Business Services",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Sole",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "-851620",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Subsea Global",
		"Issuer Group Code": "AB",
		"Security Code": "Subsea_TL",
		"Instrument": "TL",
		"Spread": "L + 700",
		"Maturity Date": "03-28-23",
		"Industry": "Business Services",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Sole",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "852294.37",
		"Event": "MV",
		"Symbol": "AB",
		"IRR": "0.1554"
	},
	{
		"Issuer Group": "US Fitness",
		"Issuer Group Code": "U",
		"Security Code": "US Fitness_Rev18",
		"Instrument": "Revolver",
		"Spread": "L + 575",
		"Maturity Date": "03-16-23",
		"Industry": "Health/Fitness",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Sole",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-30-18",
		"Cash Flow Amount": "29.79",
		"Event": "43B",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "US Fitness",
		"Issuer Group Code": "U",
		"Security Code": "US Fitness_TL18",
		"Instrument": "TL",
		"Spread": "L + 575",
		"Maturity Date": "03-19-24",
		"Industry": "Health/Fitness",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Sole",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-19-18",
		"Cash Flow Amount": "-2885065",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "US Fitness",
		"Issuer Group Code": "U",
		"Security Code": "US Fitness_TL18",
		"Instrument": "TL",
		"Spread": "L + 575",
		"Maturity Date": "03-19-24",
		"Industry": "Health/Fitness",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Sole",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "2895449.86",
		"Event": "MV",
		"Symbol": "U",
		"IRR": "0.1158"
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "92346LAA1",
		"Instrument": "Sr Nts",
		"Spread": "10.50%",
		"Maturity Date": "02-01-24",
		"Industry": "Technology",
		"Secured/Unsecured": "Unsecured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "01-25-18",
		"Cash Flow Amount": "-247115.83",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "92346LAA1",
		"Instrument": "Sr Nts",
		"Spread": "10.50%",
		"Maturity Date": "02-01-24",
		"Industry": "Technology",
		"Secured/Unsecured": "Unsecured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "02-01-18",
		"Cash Flow Amount": "12075",
		"Event": "CPN",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "92346LAA1",
		"Instrument": "Sr Nts",
		"Spread": "10.50%",
		"Maturity Date": "02-01-24",
		"Industry": "Technology",
		"Secured/Unsecured": "Unsecured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-15-18",
		"Cash Flow Amount": "-190233",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "02-15-18",
		"Cash Flow Amount": "-481680.47",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "02-15-18",
		"Cash Flow Amount": "-245385",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "02-15-18",
		"Cash Flow Amount": "-245077.5",
        "Event": "TRD",
        "Symbol": "",
        "IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "02-22-18",
		"Cash Flow Amount": "-373593.75",
        "Event": "TRD",
        "Symbol": "",
        "IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "02-22-18",
		"Cash Flow Amount": "-724360",
        "Event": "TRD",
        "Symbol": "",
        "IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-06-18",
		"Cash Flow Amount": "-78.81",
        "Event": "35B",
        "Symbol": "",
        "IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-06-18",
		"Cash Flow Amount": "296.25",
        "Event": "DCP",
        "Symbol": "",
        "IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-06-18",
		"Cash Flow Amount": "-78.709999999999994",
        "Event": "35B",
        "Symbol": "",
        "IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-06-18",
		"Cash Flow Amount": "296.25",
        "Event": "DCP",
        "Symbol": "",
        "IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "5233.21",
        "Event": "TRD",
        "Symbol": "",
        "IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "973.36",
        "Event": "IAC",
        "Symbol": "",
        "IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "973.36",
        "Event": "IAC",
        "Symbol": "",
        "IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "3005.93",
        "Event": "IAC",
        "Symbol": "",
        "IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "-1215.58",
        "Event": "TRD",
        "Symbol": "",
        "IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "1215.58",
        "Event": "TRD",
        "Symbol": "",
        "IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "-619.65",
        "Event": "TRD",
        "Symbol": "",
        "IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "619.65",
        "Event": "TRD",
        "Symbol": "",
        "IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "-619.65",
        "Event": "TRD",
        "Symbol": "",
        "IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "619.65",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "-1833.75",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "1833.75",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "-944.58",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 450",
		"Maturity Date": "01-27-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "944.58",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 1050",
		"Maturity Date": "02-01-24",
		"Industry": "Technology",
		"Secured/Unsecured": "Unsecured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "2479069.92",
		"Event": "MV",
		"Symbol": "E",
		"IRR": "-0.0202"
	},
	{
		"Issuer Group": "Verscend Technologies",
		"Issuer Group Code": "H",
		"Security Code": "LX152675",
		"Instrument": "TLB",
		"Spread": "L + 500",
		"Maturity Date": "06-01-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "02-02-18",
		"Cash Flow Amount": "-2666580",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Verscend Technologies",
		"Issuer Group Code": "H",
		"Security Code": "LX152675",
		"Instrument": "TLB",
		"Spread": "L + 500",
		"Maturity Date": "06-01-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-02-18",
		"Cash Flow Amount": "12920.39",
		"Event": "IAC",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Verscend Technologies",
		"Issuer Group Code": "H",
		"Security Code": "LX152675",
		"Instrument": "TLB",
		"Spread": "L + 500",
		"Maturity Date": "06-01-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "-6906.09",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Verscend Technologies",
		"Issuer Group Code": "H",
		"Security Code": "LX152675",
		"Instrument": "TLB",
		"Spread": "L + 500",
		"Maturity Date": "06-01-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "6906.09",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Verscend Technologies",
		"Issuer Group Code": "H",
		"Security Code": "LX152675",
		"Instrument": "TLB",
		"Spread": "L + 500",
		"Maturity Date": "06-01-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "13673.03",
		"Event": "IAC",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Verscend Technologies",
		"Issuer Group Code": "H",
		"Security Code": "LX152675",
		"Instrument": "TLB",
		"Spread": "L + 500",
		"Maturity Date": "06-01-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "6906.09",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Verscend Technologies",
		"Issuer Group Code": "H",
		"Security Code": "LX152675",
		"Instrument": "TLB",
		"Spread": "L + 500",
		"Maturity Date": "06-01-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "2733906.79",
		"Event": "MV",
		"Symbol": "H",
		"IRR": "0.2691"
	},
	{
		"Issuer Group": "Xplornet",
		"Issuer Group Code": "Y",
		"Security Code": "LX154454",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "09-09-21",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-21-18",
		"Cash Flow Amount": "-795000",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Xplornet",
		"Issuer Group Code": "Y",
		"Security Code": "LX154454",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "09-09-21",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-29-18",
		"Cash Flow Amount": "1987.5",
		"Event": "TRD",
		"Symbol": "",
		"IRR": ""
	},
	{
		"Issuer Group": "Xplornet",
		"Issuer Group Code": "Y",
		"Security Code": "LX154454",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "09-09-21",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": "794503.36",
		"Event": "MV",
		"Symbol": "Y",
		"IRR": "0.0708"
	}
];

let irr: IRRs[] = [
	{
		"Issuer Group": "Ardent Health Partners",
		"Issuer Group Code": "M",
		"Security Code": "LX171898",
		"Instrument": "Unsecured TL",
		"Spread": "L + 850",
		"Maturity Date": "03-01-23",
		"Industry": "Healthcare",
		"Secured/Unsecured": "Unsecured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 2190476.44,
		"Event": "MV",
		"Symbol": "M",
		"IRR": 0.3029 * 100
	},
	{
		"Issuer Group": "Avaya Holdings Corp",
		"Issuer Group Code": "O",
		"Security Code": "LX174166",
		"Instrument": "TLB",
		"Spread": "L + 475",
		"Maturity Date": "12-15-24",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 2016502.36,
		"Event": "MV",
		"Symbol": "O",
		"IRR": -0.0406 * 100
	},
	{
		"Issuer Group": "California Resources Corp",
		"Issuer Group Code": "P",
		"Security Code": "LX169569",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "12-31-22",
		"Industry": "Energy",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 1732982.4,
		"Event": "MV",
		"Symbol": "P",
		"IRR": -0.0613 * 100
	},
	{
		"Issuer Group": "Carlisle Foods",
		"Issuer Group Code": "V",
		"Security Code": "Carlisle_2L",
		"Instrument": "2nd Lien",
		"Spread": "L + 775",
		"Maturity Date": "03-20-26",
		"Industry": "Food & Beverage",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 1070396.25,
		"Event": "MV",
		"Symbol": "V",
		"IRR": 0.1036 * 100
	},
	{
		"Issuer Group": "Clarion Events Ltd",
		"Issuer Group Code": "J",
		"Security Code": "LX171498",
		"Instrument": "TLB",
		"Spread": "L + 500",
		"Maturity Date": "09-30-24",
		"Industry": "Business Services",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 582873.75,
		"Event": "MV",
		"Symbol": "J",
		"IRR": 0.0554 * 100
	},
	{
		"Issuer Group": "Contura Energy Inc",
		"Issuer Group Code": "W",
		"Security Code": "LX160842",
		"Instrument": "TL",
		"Spread": "L + 500",
		"Maturity Date": "11-10-25",
		"Industry": "Industrials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 676126.78,
		"Event": "MV",
		"Symbol": "W",
		"IRR": -0.1700 * 100
	},
	{
		"Issuer Group": "Corfin Industries",
		"Issuer Group Code": "I",
		"Security Code": "CORFIN_TL",
		"Instrument": "TL",
		"Spread": "L + 650",
		"Maturity Date": "02-15-24",
		"Industry": "Industrials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Sole",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 856157.97,
		"Event": "MV",
		"Symbol": "I",
		"IRR": 0.0913 * 100
	},
	{
		"Issuer Group": "EIG Investors Corp",
		"Issuer Group Code": "F",
		"Security Code": "LX171112",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "01-31-25",
		"Industry": "Financials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 217350,
		"Event": "MV",
		"Symbol": "F",
		"IRR": 0.0637 * 100
	},
	{
		"Issuer Group": "Endemol",
		"Issuer Group Code": "Q",
		"Security Code": "LX139558",
		"Instrument": "TL",
		"Spread": "L + 575",
		"Maturity Date": "08-13-21",
		"Industry": "Media/Entertainment",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 1306906.29,
		"Event": "MV",
		"Symbol": "Q",
		"IRR": -0.0679 * 100
	},
	{
		"Issuer Group": "Frontier Communications",
		"Issuer Group Code": "L",
		"Security Code": "LX164782",
		"Instrument": "TLB",
		"Spread": "L + 375",
		"Maturity Date": "06-17-24",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 2295663.52,
		"Event": "MV",
		"Symbol": "L",
		"IRR": -0.0530 * 100
	},
	{
		"Issuer Group": "Genex",
		"Issuer Group Code": "N",
		"Security Code": "LX171682",
		"Instrument": "2nd Lien",
		"Spread": "L + 700",
		"Maturity Date": "03-06-26",
		"Industry": "Healthcare",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 236394.12,
		"Event": "MV",
		"Symbol": "N",
		"IRR": 0.1866 * 100
	},
	{
		"Issuer Group": "ICR, LLC",
		"Issuer Group Code": " Z",
		"Security Code": "ICR_TL",
		"Instrument": "TL",
		"Spread": "L + 550",
		"Maturity Date": "03-26-25",
		"Industry": "Business Services",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Sole",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 1375779.2,
		"Event": "MV",
		"Symbol": "MV",
		"IRR": 0.000 * 100
	},
	{
		"Issuer Group": "InnovaCare",
		"Issuer Group Code": "S",
		"Security Code": "Innovacare_TL",
		"Instrument": "TL",
		"Spread": "L + 625",
		"Maturity Date": "03-14-23",
		"Industry": "Healthcare",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 3631776.54,
		"Event": "MV",
		"Symbol": "S",
		"IRR": 0.0145 * 100
	},
	{
		"Issuer Group": "Intelsat",
		"Issuer Group Code": "X",
		"Security Code": "LX169475",
		"Instrument": "TLB3",
		"Spread": "L + 375",
		"Maturity Date": "11-27-23",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 1808000,
		"Event": "MV",
		"Symbol": "X",
		"IRR": 0.0000 * 100
	},
	{
		"Issuer Group": "Iridium Communications",
		"Issuer Group Code": "T",
		"Security Code": "46269CAA0",
		"Instrument": "Sr Nts",
		"Spread": "10.25%",
		"Maturity Date": "04-15-23",
		"Industry": "Telecom",
		"Secured/Unsecured": "Unsecured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 374016.04,
		"Event": "MV",
		"Symbol": "T",
		"IRR": 1.0698 * 100
	},
	{
		"Issuer Group": "Loparex",
		"Issuer Group Code": "AA",
		"Security Code": "LX172480",
		"Instrument": "TLB",
		"Spread": "L + 425",
		"Maturity Date": "04-11-25",
		"Industry": "Paper & Packaging",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 203975,
		"Event": "MV",
		"Symbol": "AA",
		"IRR": 0.0000 * 100
	},
	{
		"Issuer Group": "MedRisk",
		"Issuer Group Code": "C",
		"Security Code": "LX170958",
		"Instrument": "2nd Lien",
		"Spread": "L + 675",
		"Maturity Date": "01-23-26",
		"Industry": "Healthcare",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 203149.32,
		"Event": "MV",
		"Symbol": "C",
		"IRR": 0.0521 * 100
	},
	{
		"Issuer Group": "Meredith",
		"Issuer Group Code": "A",
		"Security Code": "589433AA9",
		"Instrument": "Sr Nts",
		"Spread": "6.88%",
		"Maturity Date": "02-01-26",
		"Industry": "Media/Entertainment",
		"Secured/Unsecured": "Unsecured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 0,
		"Event": "MV",
		"Symbol": "A",
		"IRR": 0.0000 * 100
	},
	{
		"Issuer Group": "Navitas Midstream",
		"Issuer Group Code": "K",
		"Security Code": "LX170023",
		"Instrument": "TLB",
		"Spread": "L + 450",
		"Maturity Date": "12-13-24",
		"Industry": "Energy",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 1220648.1100000001,
		"Event": "MV",
		"Symbol": "K",
		"IRR": -0.0293 * 100
	},
	{
		"Issuer Group": "PetVet LLC",
		"Issuer Group Code": "G",
		"Security Code": "LX170766",
		"Instrument": "2nd Lien",
		"Spread": "L + 625",
		"Maturity Date": "01-30-26",
		"Industry": "Consumer",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 358250.96,
		"Event": "MV",
		"Symbol": "G",
		"IRR": 0.0246 * 100
	},
	{
		"Issuer Group": "Safe Fleet",
		"Issuer Group Code": "B",
		"Security Code": "LX170944",
		"Instrument": "2nd Lien",
		"Spread": "L + 675",
		"Maturity Date": "02-01-26",
		"Industry": "Industrials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 317405,
		"Event": "MV",
		"Symbol": "B",
		"IRR": 0.0000 * 100
	},
	{
		"Issuer Group": "Skillsoft Corp",
		"Issuer Group Code": "D",
		"Security Code": "LX136501",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "04-28-21",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 351056.94,
		"Event": "MV",
		"Symbol": "D",
		"IRR": -0.0363 * 100
	},
	{
		"Issuer Group": "Stepstone",
		"Issuer Group Code": "R",
		"Security Code": "LX172326",
		"Instrument": "TLB",
		"Spread": "L + 400",
		"Maturity Date": "03-27-25",
		"Industry": "Financials",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Club",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 299495,
		"Event": "MV",
		"Symbol": "R",
		"IRR": 0.0000 * 100
	},
	{
		"Issuer Group": "Subsea Global",
		"Issuer Group Code": "AB",
		"Security Code": "Subsea_TL",
		"Instrument": "TL",
		"Spread": "L + 700",
		"Maturity Date": "03-28-23",
		"Industry": "Business Services",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Sole",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 852294.37,
		"Event": "MV",
		"Symbol": "AB",
		"IRR": 0.1554 * 100
	},
	{
		"Issuer Group": "US Fitness",
		"Issuer Group Code": "U",
		"Security Code": "US Fitness_TL18",
		"Instrument": "TL",
		"Spread": "L + 575",
		"Maturity Date": "03-19-24",
		"Industry": "Health/Fitness",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Sole",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 2895449.86,
		"Event": "MV",
		"Symbol": "U",
		"IRR": 0.1158 * 100
	},
	{
		"Issuer Group": "Veritas",
		"Issuer Group Code": "E",
		"Security Code": "LX165578",
		"Instrument": "TLB1",
		"Spread": "L + 1050",
		"Maturity Date": "02-01-24",
		"Industry": "Technology",
		"Secured/Unsecured": "Unsecured",
		"Deal Type": "Opportunistic",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 2479069.92,
		"Event": "MV",
		"Symbol": "E",
		"IRR": -0.0202 * 100
	},
	{
		"Issuer Group": "Verscend Technologies",
		"Issuer Group Code": "H",
		"Security Code": "LX152675",
		"Instrument": "TLB",
		"Spread": "L + 500",
		"Maturity Date": "06-01-23",
		"Industry": "Technology",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 2733906.79,
		"Event": "MV",
		"Symbol": "H",
		"IRR": .2691 * 100
	},
	{
		"Issuer Group": "Xplornet",
		"Issuer Group Code": "Y",
		"Security Code": "LX154454",
		"Instrument": "TL",
		"Spread": "L + 475",
		"Maturity Date": "09-09-21",
		"Industry": "Telecom",
		"Secured/Unsecured": "Secured",
		"Deal Type": "Anchor",
		"Sponsor/Nonsponsor": "Non-Sponsor",
		"Cash Flow Date": "03-31-18",
		"Cash Flow Amount": 794503.36,
		"Event": "MV",
		"Symbol": "Y",
		"IRR": 0.0708 * 100
	}
];

@Injectable()
export class TransactionService {
    getCashflows() {
        return cashflow;
    }

    getIRR() {
        return irr;
    }
}